<?php
$text_dir = 'rtl';
$messages['translator']='Yoni'; //<yonidebest AT  gmail.com>
$messages['translator_link']='http://he.wikipedia.org/wiki/%D7%9E%D7%A9%D7%AA%D7%9E%D7%A9:Yonidebest'; 
$messages['lang']='שפה';
$messages['project']='מיזם';
$messages['article']='ערך';
$messages['needle']='תוכן לחיפוש';
$messages['skipversions']='דלג תמיד על x גרסאות';
$messages['ignorefirst']='דלג על x הגרסאות הראשונות';
$messages['limit']='מספר גרסאות לבדיקה';
$messages['start_date'] = 'תאריך התחלה';
$messages['order'] = 'סדר הבדיקה';
$messages['newest_first'] = 'החדש ראשון';
$messages['oldest_first'] = 'הישן ראשון';
$messages['search_method'] = 'שיטת חיפוש';
$messages['linear'] = 'לינארי';
$messages['interpolated']='אינטרפולצי (מהיר יותר עם יותר גרסאות)';
$messages['ignore_minors']='התעלם משינויים מינוריים (ניסיוני)';
$messages['start'] ='התחלה';
$messages['reset'] ='איפוס';
$messages['manual'] ='הסברים';
$messages['contact']='יצירת קשר';
$messages['wrong_skips'] = ' שגיאה: אם נדלג על __VERSIONSTOSKIP__ הגרסאות הראשונות, אף אחד מ-__VERSIONSTOSEARCH__ הגרסאות שיש לבצע בהן את החיפוש ייבדק.';
$messages['search_in_progress'] = 'מתבצע כרגע חיפוש של הטקסט <b>_NEEDLE_</b> בגרסאות הקודמות של הערך _ARTICLELINK_...';
$messages['execution_time'] = 'זמן חיפוש: _EXECUTIONTIME_ שניות';
$messages['versions_found'] = 'נמצאו _NUMBEROFVERSIONS_ גרסאות';
$messages['binary_test'] = 'משווה הבדלים ב-_FIRSTDATEVERSION_ בין _FIRSTNUMBER_ לבין _SECONDNUMBER_ כשהמקור הוא _SOURCENUMBER_:';
$messages['insertion_found'] = 'נמצא שיבוץ בין LEFT_VERSION לבין RIGHT_VERSION';
